### ISSUE TITLE
Installed the plugin but it seems there is a server side component that I am not sure how to setup

### ISSUE THREAD

**Issue by ChrisMagnuson** [grafana/grafana-csv-datasource#1]
I have installed the plugin and when I add a CSV datasource it is looking for an http url.

I originally was hoping to access the CSV files locally on the server give that the section header is http I am guessing `file://` URI schemes wouldn't be supported in the URL field.

Is there another server component to this plugin kind of like [CSVServer](https://github.com/michaeldmoore/CSVServer) or is this just the URL to call that responds with CSV data in the body of the response?

**Comment by marcusolsson** [comment]
Currently, the plugin only supports CSV over HTTP. There's no server needed other than the one hosting the CSV file. If you just want to try it out first, you can create a [GitHub Gist](https://gist.github.com) and copy the raw URL.

Here's a URL to [one of the data sets](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv) from John Hopkins University.

Just copy-paste the following URL in the URL field of the plugin:

https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv
