### ISSUE TITLE
Love this plugin

### ISSUE THREAD

**Issue by G0nz0uk** [grafana/grafana-csv-datasource#10]
I’ve spent weeks trying to get my Citrix Powershell outputs into Grafana.  Some I have via the Influx Powershell module, but others I haven’t.  Now I simply export to csv to my IIS web server every 5 mins and import using this plugin and all is good.  Thanks!!

One think it didn’t wonder about it thresholds/Colour/Mappings.  I have a some cells in my CSV that say “failed” which is correct but I’d like a way to show that cell as Red and others with different colours.

Anyway fantastic work!

**Comment by marcusolsson** [comment]
Thank you for your kind words! 

As for displaying "failed" as red depends on the visualization you use rather than the data source. Unfortunately, I'm not aware of setting color based on text. If you do find a way, I'd be interested to know!
