### ISSUE TITLE
Is it possible to show a cumulative graph?

### ISSUE THREAD

**Issue by radoeka** [grafana/grafana-csv-datasource#103]
I have the grafana cvs plugin working nicely.  Just wondering whether it is possible to show the data as cumulative graph.

Would it be possible by using Grafana's transform functionality?

Or with the cvs plugin - expression functionality?  
I had a look at this, but I don't understand how it works.
Are there examples of how to use this?

E.g. When I have a table with the following columns:
Timestamp,Total,Team1,Team2

Would it be possible to calculate the value for Team3 as: Team3 = Total - Team1 - Team2

Is it possible to negate a value, for example:
Team4 = Team2 * -1

**Comment by marcusolsson** [comment]
There's currently no support for any processing or filtering, but there's a feature request to add it in #58. Closing as duplicate for now. Let me know if you think otherwise.
