### ISSUE TITLE
Transform Mean value returns NaN

### ISSUE THREAD

**Issue by bayview-gord** [grafana/grafana-csv-datasource#113]
After applying a transformation, Max returns a value, Mean returns NaN.
Field 5 Max
39.23
Field 5 Count
10.00
Field 5 Mean
NaN

**Comment by marcusolsson** [comment]
This sounds like a general Grafana question to be honest. My bet is that your result contains missing values. Closing as it doesn't feel related to the plugin. Let me know if you think otherwise.
