### ISSUE TITLE
Data does not have a time field

### ISSUE THREAD

**Issue by sonali0610** [grafana/grafana-csv-datasource#114]
actually i was using a time series  data  after using my query i am getting data into table but unable to fetch it on time series graph it keeps on showing as data doesnot have a time field.

**Comment by aleks2a** [comment]
Same issue, I tried a CSV files with a few different date formats, but getting the same message: "Data does not have a time field".

**Comment by anetanel** [comment]
Seems that time needs to be in this format: "2021-08-19T14:42:40.583563Z"

**Comment by Shogan** [comment]
Check your time format is supported. Here is a simple format to try with:

`2021-06-01 11:32:59`

Then ensure your model fields are setup correctly. For example, if your time/date column is called "Date" then ensure you have added a **Field** called `Date`, with the **Type** set to `Time`.

In my attached example I am using a Date field for the timestamp, and have a few other columns with names such as Render(msec), Physics(msec), etc...

![example-fields](https://user-images.githubusercontent.com/814180/131375607-e4d4be9c-c580-43f4-beb7-7a5d9ba83cbf.png)

That should do the trick and you won't see the "Data does not have a time field" error anymore.

**Comment by aleks2a** [comment]
Thank you @Shogan, my mistake was that I didn't select Field `Date` as type `Time`. Works now.
