### ISSUE TITLE
wrong link to the grafana plugin page on the github page 

### ISSUE THREAD

**Issue by ouinouin** [grafana/grafana-csv-datasource#12]
correct link : https://grafana.com/grafana/plugins/marcusolsson-csv-datasource/installation
link found in the about section of the plugin in your github page : https://grafana.com/plugins/grafana-csv-datasource

hope this helps

**Comment by marcusolsson** [comment]
Thanks for letting me know! Would you like to submit a PR for this yourself?

**Comment by ouinouin** [comment]
hi, lacking of time for this unfortunately. i ll try to have some time to dig deeper in the csv time/date issues :-)
