### ISSUE TITLE
ARMv7 Version

### ISSUE THREAD

**Issue by muraimi** [grafana/grafana-csv-datasource#13]
Hello Marcus!

Is it possible to compile this plugin for ARMv7 (raspberry pi)?

Thx and BR
Rainer

**Comment by marcusolsson** [comment]
Sure! I've published a new release [v0.3.0](https://grafana.com/grafana/plugins/marcusolsson-csv-datasource?pg=plugins&plcmt=featured-undefined&version=0.3.0) with binaries for ARM. Let me know if you have any trouble!
