### ISSUE TITLE
Windows: Paths with backslashes don't work

### ISSUE THREAD

**Issue by marcusolsson** [grafana/grafana-csv-datasource#14]
Reported in https://github.com/marcusolsson/grafana-csv-datasource/issues/6#issuecomment-755061701:

> On Windows 10, importing files with backslashes in the path fails, e.g. c:\temp\file.csv, whereas importing files with forward slashes succeeds, e.g. c:/temp/file.csv

**Comment by KBChaithra** [comment]
![image](https://user-images.githubusercontent.com/90372509/133282691-88c4e0f8-6c7d-4998-af02-37dc753a2fb0.png)
Even with forward slashes importing files is failing
