### ISSUE TITLE
Unable to graph data

### ISSUE THREAD

**Issue by suntong** [grafana/grafana-csv-datasource#15]
Is it true that it is unable to graph data from the `grafana-csv-datasource`? I got:

![image](https://user-images.githubusercontent.com/422244/104230942-37fbd300-541c-11eb-9fe0-6bd540cf24fc.png)

And there is no way I found to switch it to graph view, only table view.

**Comment by marcusolsson** [comment]
You _can_ graph data using the CSV data source! 

The Graph panel requires a **Time** field and a **Number** field. The error you're getting means that the query response is missing one or both of the required fields.

The plugin tries to guess the data type (CSV is just text), but if you want to be sure that you have the correct field you can set a schema explicitly.

If you're able to give me a sample of the CSV data you want to graph, I can give you better answer.

**Comment by suntong** [comment]
Oh, thanks for the reply. that's good news. I'll give it a try...
