### ISSUE TITLE
Ability to compare 2 or more load tests

### ISSUE THREAD

**Issue by suntong** [grafana/grafana-csv-datasource#16]
Hi, 

I'm in the situation that I need to store JMeter test results as CSV files instead of into DB. 

Would I be able to somehow compare 2 or more load tests stored in CSV files with this `grafana-csv-datasource`? 
I mean, to compare in the Graph panel, which requires a Time field and a Number field. The problem to me is that different tests have different timestamps. So,

- How can I chart 2 or more load tests in the same Graph panel?
- How to make sure they line up nicely instead each in their own time period?

Thx!

**Comment by marcusolsson** [comment]
Currently, each data source corresponds to a single CSV file. If you have multiple CSV files, you can create multiple CSV data sources and combine them in a graph using the Mixed data source. It's a little cumbersome, but if you have an idea of what would make it easier, I'd love to hear it!

**Comment by suntong** [comment]
Gotya. I'll play around and see how things can possibly be improved. Thanks!
