### ISSUE TITLE
Plugin can not be health checked

### ISSUE THREAD

**Issue by juaniyyoo** [grafana/grafana-csv-datasource#164]
Hello, 

The plugin is not working and can not be health checked.

I tried installing and uninstalling it in grafana GUI and grafana-cli. However it keeps sending back "Plugin unvailable" message with a **503** return code from `https://[HOST]/api/datasources/[id]/health`. Aside, plugins such as prometheus work.

I am using the default `grafana/grafana` latest docker image. 
Grafana cli version is : **Grafana CLI version 8.3.6**

**Here are grafana logs :**

    t=2022-02-16T19:52:01+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/live/ws status=0 remote_addr=[my local address] time_ms=2 size=0 referer=
    t=2022-02-16T19:56:26+0000 lvl=eror msg="Plugin unavailable" logger=context userId=1 orgId=1 uname=admin error="plugin unavailable" remote_addr=[my local address]

**Browser logs :**

    WebSocket connection to 'ws://[SERVER ADDRESS]:3000/api/live/ws' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED

Everything is working up for other plugins.

Would you have any idea about it ?

**Comment by marcusolsson** [comment]
Hm. `Plugin unavailable` together with a 503 typically means that the plugin has crashed. Do you have any idea of how I could reproduce this on my end? Are you using a public URL? Or are you reading a local file?

**Comment by zoltanbedi** [comment]
I'm going to close this issue as no answer was given.
