### ISSUE TITLE
Upgrading

### ISSUE THREAD

**Issue by G0nz0uk** [grafana/grafana-csv-datasource#17]
Hello,

Apologies as it’s not an issue, but wasn’t sure how to contact you.

What a great plugin, I’ve been using it for a while on my Linux Grafana boxer work.

How do I check what version I’m using?
How can I upgrade to the latest?

thanks

**Comment by marcusolsson** [comment]
Thanks, and no worries!

I've enabled [Discussions](https://github.com/marcusolsson/grafana-csv-datasource/discussions) if you have future questions. It might be useful for anyone with the same question as issues tend to disappear after they're closed.

You should be able to see the current version if you run:

```
grafana-cli plugins ls
```

To update you should be able to run:

```
grafana-cli plugins update marcusolsson-csv-datasource
```

Hope that helps!

**Comment by G0nz0uk** [comment]
Thanks,  I’m now on version 0.3.0 but all my CSV dashboards no longer work.

Can I put 0.1.0 back on easily?

I have a snapshot I can roll back to also.

**Comment by G0nz0uk** [comment]
I have rolled back the snapshot and back on version 0.1.0 and it’s now working again.

**Comment by marcusolsson** [comment]
That's a shame :( I'd love to know more about the issues you're seeing so that you can update. Are you getting any errors?

**Comment by G0nz0uk** [comment]
I don’t see any errors, just my panels don’t display anything.  I have around 10 csv data sources I use for Citrix.  They all stopped when I went to 0.3.0, so rolled back.

I just point to the CSV file on an IIS server that I produce via powershell.  In Grafana I just use the Delimiter as Comma and it shows.

How do I get to the error logs?

Is there a method I can upgrade to 0.3.0 again and roll back to 0.1.0 again?

Thanks

**Comment by andywhiteglobal** [comment]
Is there a quick way to downgrade from 0.3.0 to 0.1.0 so I can look at what the differences might be?

**Comment by marcusolsson** [comment]
This should work:

```
grafana-cli plugins install marcusolsson-csv-datasource 0.1.0
```

It would be really helpful for me know whether this is an issue with connecting to the CSV file, or whether it's related to the actual CSV content.

For example, does it work if you [create a gist](https://gist.github.com/) with the same CSV content and add it as a data source?

**Comment by G0nz0uk** [comment]
I'll try the downgrade and gist test.

I tried updating again and the error I get is "unsupported storage type"

**Comment by marcusolsson** [comment]
Oh! I'm sorry about that. v0.3.0 introduced support for local files. In your data source config, you can now select between two different storage types: HTTP and Local.

The plugin should've defaulted to HTTP for existing users, but it seems like it didn't. Try going to the data source config page and clicking 'HTTP' (that should set the storage type). If that doesn't work (and you don't want to recreate the data source) we can edit the dashboard JSON instead to add it.

**Comment by G0nz0uk** [comment]
I have changed it from local to http and when I hit test I get:

Get "https://myiisserver.local/myoutput.csv": net/http: invalid header field name ""

I have 8 CSV datasources and they all seem to do the same.  These are powershell scripts that output to CSV.

If I downgrade to 0.1.0 all is good again.

I use the Delimeter as Tab

**Comment by marcusolsson** [comment]
Hm. I wonder if this is related to Custom headers. It looks like the plugin is sending an empty HTTP header. Are you currently setting any custom HTTP headers?

**Comment by G0nz0uk** [comment]
Hmm sorry could you explain that a little more in terms of custom headers?  

One of the csv's looks like this, I've had to remove private information though.

<img width="1006" alt="Screenshot at Jan 19 16-54-55" src="https://user-images.githubusercontent.com/15994497/105066843-18e1ee80-5a77-11eb-95a3-12874ae837c8.png">

If I look on IIS which doesn't have excel and opens with Wordpad it looks like this for the first 2 lines:

"Users","Apps","LogonTime","UserIP","UserDevice","VMIP","VDI Name","DG","SessionState","PowerState","FaultState"
"DOMAIN\joe","Word","19/01/2021 09:03:34","10.1.2.3","MyPC","10.5.6.7","VDIW10123","W10_Standard","Active","On","None"

**Comment by marcusolsson** [comment]
I think I've managed to reproduce this. Will do some troubleshooting on my part and update you as soon as I know more.

**Comment by G0nz0uk** [comment]
wow thanks!

**Comment by marcusolsson** [comment]
I've published 0.3.1, which contains a fix, arguably for the symptom rather than the cause. Could you try and see if that fixes your problem?

**Comment by G0nz0uk** [comment]
I get the same issue I'm afraid on all the dashboards we run.  Just says 'unsupported storage' type.

If I then go and look at the data source and test it I get the all green, but of I go back to the panel in no longer says 'unsupported storage' but 'parse error on line 1, column 22: bare " in non-quoted-field'

**Comment by G0nz0uk** [comment]
yes it's using 
5.4.0-62-generic #70-Ubuntu SMP Tue Jan 12 12:45:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by G0nz0uk** [comment]
Hi @marcusolsson I was just wondering if there is anymore testing I can do?

**Comment by marcusolsson** [comment]
I haven't had a chance to look at this yet, unfortunately.

Do you see the `'parse error on line 1, column 22: bare " in non-quoted-field'` for all your data sources, or is it only certain CSV files?

Also, in the meantime, could you maybe try removing the data source and adding it back again to make sure there's no settings from the previous versions that interfere?

I'll try to get to this during the week. I haven't heard about this issue from other users, so I'm thinking it's related to configuration or your specific data. 

Thanks for your patience on this!

**Comment by G0nz0uk** [comment]
So I have just updated to 0.3.1 and restarted Grafana and all my CSV panels how as 'Unsupported file type'.

I added a new datasource and tested it and it said 'ok' I then when and created a new cvs panel table and got the 'parse error on line 1, column 22: bare " in non-quoted-field'

Rolled back to 0.1.0 and all 6 panels are working again.

**Comment by marcusolsson** [comment]
I googled on the error and it looks like it's due to a single double-quote in the cells.

For example,

```
foo, bar, tes"t, baz
```

or due to single quote in a quoted cell

```
"I", "can't", "even"
```

It looks like we can allow this by enabling lazy quotes:

From https://golang.org/pkg/encoding/csv/:

```go
    // If LazyQuotes is true, a quote may appear in an unquoted field and a
    // non-doubled quote may appear in a quoted field.
    LazyQuotes bool
```

Not sure why this is working in 0.1.0 though. Is there any way you could verify if this is indeed what causes the error?

**Comment by marcusolsson** [comment]
I've published 0.3.2 that enable lazy quotes. Let me know if it works.

**Comment by G0nz0uk** [comment]
Thanks, I will test in the morning and let you know how I get on.  It it works I’ll see where these lazy quotes are, some of the CSVs have people names in them which have apostrophes in them, could that be it?

**Comment by G0nz0uk** [comment]
Same issue, this is the output of one of the csv files.  I've removed the other users as it would be long.  It has the column names at the top and then the user session info for their Citrix session:

"Users","Apps","LogonTime","UserIP","UserDevice","VMIP","VDI Name","DG","SessionState","PowerState","FaultState"
"DOMAIN\bob","CSS Live LD_1-1","04/02/2021 15:58:53","10.17.217.244","HHNWL414","10.217.14.7","LD-W1042","W10_Standard","Active","On","None"

what I see

![image](https://user-images.githubusercontent.com/15994497/106931618-acb9e880-670e-11eb-9623-2a521e118bbd.png)

**Comment by marcusolsson** [comment]
Thanks for the test data. It seems to work for me on Grafana 7.3.6 with the latest plugin version 0.9.2.

<img width="868" alt="Screen Shot 2021-02-05 at 07 02 30" src="https://user-images.githubusercontent.com/8396880/106995886-2938df80-6780-11eb-8846-4b0041d081ff.png">

**Comment by G0nz0uk** [comment]
Can I send you the whole csv to test?

I'm on 7.3.7, how do I get my plugin version as I though you were on 0.3.2 not 0.9.2?

https://pastebin.com/CKRkQrb0

![image](https://user-images.githubusercontent.com/15994497/107027785-88105000-67a4-11eb-8587-d3fe4578e8c0.png)


Thanks

**Comment by marcusolsson** [comment]
Sorry, I'm mixing up the versions from my plugins 😅 0.3.2 is indeed the latest one.

I'm able to load the CSV you linked to successfully. I tried loading it one 0.2.0 and 0.3.0 which also worked. It leads me to believe that the error is related to your data source config rather than the data itself. 

Are you still getting the `bare " in non-quoted-field` error?

(Also, feel free to delete the CSV data on the link you sent me)

**Comment by G0nz0uk** [comment]
I got the 'Unsupported file type'

Do you have a screenshot of you datasource so I can compare?

my csv's sit on IIS btw, I guess I could try locally to see if it's that?

**Comment by marcusolsson** [comment]
Do you mean 'Unsupported storage type', or _file_ type? I thought you got past that one?

> but of I go back to the panel in no longer says 'unsupported storage'

This is what I did:

1. I copied the link to the raw CSV that you linked in this thread
2. Created a new CSV data source
3. Pasted the URL
4. Went to Explore—works without any changes to query editor

**Comment by G0nz0uk** [comment]
1. I stop grafana
2. update from 0.1.0 to 0.3.2
3. I start Grafana
4. Check my CSV panels
![image](https://user-images.githubusercontent.com/15994497/107077073-443d3b00-67e4-11eb-80e4-bdca40e2449a.png)

csv's just live in IIS on a remote server

Scratching my head.  I have Grafana at home so might try there, but don't have a web server.

**Comment by marcusolsson** [comment]
Ok, I've published 0.3.3 that defaults to HTTP if there's no storage type set. Could you try that one maybe?

**Comment by G0nz0uk** [comment]
Sorry about this issue as it's only me, I will try on my home lab too and see what the results are.  I have just upgraded to 0.3.2 ( whoops I mean 0.3.3) and all my panels now say:

![image](https://user-images.githubusercontent.com/15994497/107112779-1bec2580-6852-11eb-8885-679bdf7a100f.png)

Roll back to 0.1.0 and all is good.

I wonder if it's the upgrade process?  I wonder if you created a 0.1.1 (or something you haven't used) and made no changes to 0.1.0 and then I try the upgrade?  And see if it still works.

**Comment by marcusolsson** [comment]
No worries. We'll get it working. Did you try 0.3.3 yet?

**Comment by G0nz0uk** [comment]
Sorry that was a typo, I meant 0.3.3.

I’ve corrected my previous post.

**Comment by marcusolsson** [comment]
That feels like progress though. I _think_ that error tells you that you have rows with different number of columns in your data.

**Comment by G0nz0uk** [comment]
Update:

So I set this all up at home on my 7.3.7 Grafana server with CSV 0.1.0 and the csv is good like at work.

I upgrade to 0.3.3 and I get:

![image](https://user-images.githubusercontent.com/15994497/107123595-48c22c00-6896-11eb-86ce-f1f15aea3cfa.png)

Roll back to 0.1.0 and all is good again.

**Comment by marcusolsson** [comment]
Are you using the same data as before? I can reproduce your error with the following CSV:

```
foo, value
john, 10, foo
lily, 20
```

Notice that the second line has three columns, whereas the others have two. Same thing happens if you have too few columns:

```
foo, value
john
lily, 20
```

Could you look at line 8 in your CSV data and see if it's missing, or has more columns than there are headers?

**Comment by G0nz0uk** [comment]
Yeah I'm using https://pastebin.com/Y9HcXr87

I just saved as a csv in Excel and put in on my IIS server.

![image](https://user-images.githubusercontent.com/15994497/107125722-6944b300-68a3-11eb-81d1-8f332ed62375.png)

and when I role back to 0.1.0

![image](https://user-images.githubusercontent.com/15994497/107125791-c2144b80-68a3-11eb-86ac-bd095c54dd1b.png)

Could it be the empty cell in line 7 rather that line 8?

**Comment by marcusolsson** [comment]
Hm. I wonder if this is a Windows-specific thing, since I have no trouble reading the file you just gave me (macOS). 

Is there any way you can remove the offending lines until you get it working, and then send me the specific lines?
