### ISSUE TITLE
Bug: Empty rows on column types "time" cause unwanted behavior

### ISSUE THREAD

**Issue by gdassori** [grafana/grafana-csv-datasource#170]
Hello. Thanks for your plugin.

If I define the type `Time` on a column, and the CSV data-source return some empty rows, the whole table values are not rendered:

As you can see in the screenshots, if I set the type `String` some values are returned (and turned into NaN by the table panel column override rules), but if I set `Time` (which would allow sorting and avoid the NaN glitches) nothing is shown.

(Sorry for the wild blurring, but personal information all around).

![image](https://user-images.githubusercontent.com/5659270/156365171-66d70067-0835-4eae-b274-bb542e32341a.png)

![image](https://user-images.githubusercontent.com/5659270/156365491-2a7520d4-79e3-499d-9c29-e0e6ea9c997c.png)

**Comment by marcusolsson** [comment]
Thanks for reporting! I can confirm that I'm able to reproduce this with the following CSV data:

```csv
time,value
,20
2022-03-02 11:52:57, 10
,20
2022-03-02 11:44:06, 10
,20
```

<img width="942" alt="Screenshot 2022-03-09 at 16 26 19@2x" src="https://user-images.githubusercontent.com/8396880/157473153-9e2db3ce-d7f7-4c1a-9576-da2ef5a940c1.png">

**Comment by lalithkumar-toast** [comment]
@marcusolsson  Is it possible to to convert integer to data time value. As Checked the code based it is able to convert the values to int to date time. But currently I am using Dropwizard & it gives the headed name as "t". Can you help me on this.

Sample data:
t,count,mean_rate,m1_rate,m5_rate,m15_rate,rate_unit
1651239776,0,0.000000,0.000000,0.000000,0.000000,events/day
1651239836,0,0.000000,0.000000,0.000000,0.000000,events/day
1651239896,0,0.000000,0.000000,0.000000,0.000000,events/day
1651239956,0,0.000000,0.000000,0.000000,0.000000,events/day
1651240016,0,0.000000,0.000000,0.000000,0.000000,events/day
1651240076,0,0.000000,0.000000,0.000000,0.000000,events/day

So the field one is Unix Timestamp.  It would be a great help.

**Comment by MarcosSB** [comment]
I am able to reproduce it as well
![image](https://user-images.githubusercontent.com/5909143/185140752-52d31c19-e64b-49de-9024-476e9898417d.png)
But if you use an alias "time" the dates are correct!
![image](https://user-images.githubusercontent.com/5909143/185140965-f25525b8-3bfe-49bf-9117-a96afb5b15b4.png)

**Comment by yesoreyeram** [comment]
Hiya. Can you try this with Infinity datasource plugin and see if you are having issues with it as well?

In an effort to unify the JSON/CSV/XML datasource plugins in Grafana, we are planning to deprecate this plugin in favour of [Infinity datasource plugin](https://grafana.com/grafana/plugins/yesoreyeram-infinity-datasource/) which is actively maintained by Grafana. So I would recommend you to consider switching to Infinity datasource plugin insead.
