### ISSUE TITLE
An unexpected error happened when selection "Local"

### ISSUE THREAD

**Issue by boaz-raz** [grafana/grafana-csv-datasource#188]
When I add the CSV data source and select "Local" I get the following error. I"m using my local host for testing with grafana 7

```
An unexpected error happened
Details
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

    in Unknown
    in div
    in t
    in form
    in div
    in div
    in t
    in div
    in div
    in div
    in t
    in t
    in div
    in t
    in t
    in x
    in ConnectWithCleanUp(Connect(t))
    in r
    in Unknown
    in t
    in Unknown
    in m
    in Unknown
    in Unknown
    in t
    in t
    in s
```

**Comment by marcusolsson** [comment]
Hey! Could you share the plugin version and the exact version of Grafana you're seeing this on? This error typically appear when you're running the plugin on an unsupported version of Grafana. The latest plugin release requires [>=7.3.0](https://github.com/marcusolsson/grafana-csv-datasource/blob/902eac08e25003290cabebd4d7c62560a5717285/src/plugin.json#L46).

**Comment by boaz-raz** [comment]
Thanks for the replay. checking the UI I see v7.0.0 (aee1438ff2).
You can close it... sorry I didn't see I had an older version :/ 
it seems working now with 7.3
