### ISSUE TITLE
missing leading zeros when showing digital string value on tableview

### ISSUE THREAD

**Issue by poulls** [grafana/grafana-csv-datasource#191]
The raw data line is "...,000408,...." in csv files while showing "408" on tableview but "000408" in Inspect/Data un Formated-data mode. 
The field type in tableview has been set to "String".
Please help tale a look.
![1649325816(1)](https://user-images.githubusercontent.com/3113667/162176122-d0b3174b-4c55-4d52-90ce-c3ea81c75584.png)
![1649325816](https://user-images.githubusercontent.com/3113667/162176179-b85d2086-e556-4515-9d26-e34077ab7ce0.png)

**Comment by gabor** [comment]
hi, @poulls , could you try with a current grafana version? i tried it with grafana11, and i see `000408` even in the table.

**Comment by gabor** [comment]
as we got no new information, we're closing the issue. we can reopen it if we get new info.
