### ISSUE TITLE
Localhost version not working

### ISSUE THREAD

**Issue by EslamGitHub** [grafana/grafana-csv-datasource#192]
![image](https://user-images.githubusercontent.com/25060415/162691920-2838392e-9dd2-4454-8dd5-a1ae8ec396a9.png)

Hi everyone, I'm facing this issue with below text 

`Fetch error: 404 Not Found Instantiating http://localhost:3000/public/app/plugins/datasource/marcusolsson-csv-datasource/module Loading app/plugins/datasource/marcusolsson-csv-datasource/module`

I've tried my best to look for a solution but no luck. I followed the instruction on the plugin website but still I can't get the plugin to work. 

Did I missed any thing to make it work?

Regards,

**Comment by zoltanbedi** [comment]
You probably forgot to restart grafana.
