### ISSUE TITLE
Space as Delimiter

### ISSUE THREAD

**Issue by mrbesen** [grafana/grafana-csv-datasource#193]
I have a unconventional csv file, that has space as delimiter. So i thought, i can just add that to the delimiter list and done.
But i guess there are many more weird csv files with very unconventional delimiters. So adding a "custom Delimiter" option would be great to define any delimiter a user could want. Sadly i am not familiar with reactjs at all.
I tried my best to implement it here: 

https://github.com/mrbesen/grafana-csv-datasource

but it wont quite work as expected. (Hence no PR) Maybe someone more experienced might have a look at it?

I wanted to make the Input hide, when "Custom Delimiter" is not selected, but that is way out of my reach.

**Comment by zoltanbedi** [comment]
Adding a new option (Space) here https://github.com/grafana/grafana-csv-datasource/blob/main/src/components/FieldEditor.tsx#L25 would be good I think.

**Comment by mrbesen** [comment]
Yes, that would solve my problem, but maybe there is someone elese having some obscure delimiter that we cant even think of. So i would just allow for a custom string as delimiter.

**Comment by yesoreyeram** [comment]
Hiya. I would recommend using Infinity datasource plugin which supports custom delimiter and also now actively maintained by Grafana Labs.

Eventually in an effort to unify our JSON/CSV plugins, we are planning to deprecate this CSV plugin in favour of Infinity datasource plugin.
