### ISSUE TITLE
stat permission denied error when when all files and folders have adequate permissions

### ISSUE THREAD

**Issue by sravanthnag** [grafana/grafana-csv-datasource#196]
Which user is used to fire the stat command by this plugin ?

With root user, local user, I can stat the directory or file in Linux but from Grafana add datasource section, whenever I use save and test, I get the error that 

stat : <full directory path>/ : permission denied

I tried giving exact file name. Even then it gets into same error

stat : <full directory path>/sample.csv : permission denied

**Comment by rfkbri** [comment]
Same issue here. Have you been able to figure the fix?

**Comment by SaradhiD** [comment]
Facing same issue with

stat /home/backup_log.csv: permission denied

**Comment by ZRunner** [comment]
Same thing here. Any idea?

**Comment by d-k-bo** [comment]
In my case, it didn't work because I used a CSV which lived in `/home`. See https://github.com/fr-ser/grafana-sqlite-datasource/blob/master/docs/faq.md#i-have-a-permission-denied-error-for-my-database

**Comment by b5y** [comment]
Thanks @d-k-bo ! Your solution perfectly works for me.

**Comment by gabor** [comment]
hi @sravanthnag, sorry, we cannot do much here, for some reason your operating system does not allow the grafana-server-process access to that file. the solution will be specific to your setup. i recommend checking the article linked in https://github.com/grafana/grafana-csv-datasource/issues/196#issuecomment-1496387305 too.
