### ISSUE TITLE
Feature S3 source

### ISSUE THREAD

**Issue by mysiki** [grafana/grafana-csv-datasource#201]
Hello,

you thinks it's possible to add S3 storage as data source ? 

Thanks.

**Comment by ajunior** [comment]
It'd be great to have CGS as data source as well.

**Comment by Prashantped** [comment]
trying to add s3 as a data source using the plugin, data source is connected but when creating a dashboard its showing no data.
need help on this

**Comment by zoltanbedi** [comment]
You can use an S3 bucket but you have to make it publicly available.
