### ISSUE TITLE
local data source not working

### ISSUE THREAD

**Issue by radu-boboc** [grafana/grafana-csv-datasource#203]
Hello,

I just installed your plugin, over my grafana 8.5.0 and I am failing at adding a local csv datasource.
I created in temp a file called test.csv
`ll /tmp/test.csv
-rw-rw-rw- 1 root root 7.9K Jun 12 11:47 /tmp/test.csv
`
Added as a datasource:
![image](https://user-images.githubusercontent.com/99618192/173225210-000c386f-72e6-44b9-8d2b-052e2b985882.png)

and got this error:
`stat /tmp/test.csv: no such file or directory`

However, if I run that command on the server it works just fine:
` stat /tmp/test.csv
  File: /tmp/test.csv
  Size: 7996            Blocks: 16         IO Block: 4096   regular file
Device: fd00h/64768d    Inode: 3014716     Links: 1
Access: (0666/-rw-rw-rw-)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2022-06-12 11:47:30.831015381 +0300
Modify: 2022-06-12 11:47:19.750816523 +0300
Change: 2022-06-12 11:48:17.287808559 +0300
`

Am I missing something?

**Comment by spiltmidi** [comment]
You need to input your full path to the .csv file. e,g, c:/test/test.csv
