### ISSUE TITLE
Wrong behavior running on s390x platform

### ISSUE THREAD

**Issue by andersonz1** [grafana/grafana-csv-datasource#213]
Hello, I've built the plugin to IBM s390x platform with no code changes.
The plugin is running but with unexpected csv parsing.
Test source I'm trying is: https://people.sc.fsu.edu/~jburkardt/data/csv/airtravel.csv
The queries' result is:
[csv_error.csv](https://github.com/marcusolsson/grafana-csv-datasource/files/9637225/csv_error.csv)

<img width="1410" alt="csv_error" src="https://user-images.githubusercontent.com/37312705/192061096-37920a02-edf8-4bf7-a501-0e040184b10d.png">

Log of server:
[grafana.log](https://github.com/marcusolsson/grafana-csv-datasource/files/9637279/grafana.log)

Any idea about what can it be ?
Thank you very much,
Anderson

**Comment by andersonz1** [comment]
Any idea about this issue ? thanks

**Comment by pholm07** [comment]
I'm trying to build from source on s390x, but cannot find documentation on how to do.
Also have you solved the csv parsing error?
Thanks
Peter

**Comment by andersonz1** [comment]
Hey Peter, I did that, this is available on my github:https://github.com/andersonz1/grafana-infinity-datasource
Let me know if it works for you.Thnaks, Regards,Anderson 


    Em terça-feira, 3 de janeiro de 2023 11:12:40 BRT, pholm07 ***@***.***> escreveu:  
 
 


I'm trying to build from source on s390x, but cannot find documentation on how to do.
Also have you solved the csv parsing error?
Thanks
Peter

**Comment by pholm07** [comment]
OK so you modified the Infinity datasource. But how do I install the plugin?
In your doc directory install.md you say I can use
grafana-cli --pluginUrl https://github.com/andersonz1/grafana-infinity-datasource/releases/download/v1.0.0/yesoreyeram-infinity-datasource-1.0.0.zip plugins install yesoreyeram-infinity-datasource
But this command fails as there is no releases subdirectory.
Thanks
Peter
