### ISSUE TITLE
Unable to reference Variable in Grafana using CSV datasource

### ISSUE THREAD

**Issue by sizanvenk** [grafana/grafana-csv-datasource#218]
What happened: Not able to reference Variables in Transform section

What you expected to happen: Need to change graphs whenever new selection is made from the dropdown list of variables, dynamically.

How to reproduce it (as minimally and precisely as possible): Use CSV data Source, Create a Custom drop down variable list. (image attached)

Anything else we need to know?:

Environment:

Grafana version: 8.5.5
Data source type & version: CSV
OS Grafana is installed on: Open Source Grafana
User OS & Browser: Windows
Grafana plugins: CSV
Others:

![image](https://user-images.githubusercontent.com/39165977/194750447-1ec8fdc0-657d-4fe1-959d-dbfabc25d1f5.png)

**Comment by Yhaja10** [comment]
Did you find some way to do it?  I have a dropdown list of variables but doesn’t filter any graph
