### ISSUE TITLE
Legend values (e.g. min/max/avg/stddev) not computed as expected

### ISSUE THREAD

**Issue by xavierog** [grafana/grafana-csv-datasource#231]
Hello,

When using a CSV datasource to feed a time series panel, legend values such as minimum, maximum, mean, standard deviation, etc. are computed based on the entire CSV dataset.
Instead, most users expect these data to reflect the currently selected timeframe.

According to similar issues [here](https://community.grafana.com/t/min-max-values-for-the-displayed-time-range/3777) and [there](https://community.grafana.com/t/update-min-max-in-legend/45804), it is a matter of integrating $__timeFilter into the query. However, unless I am mistaken, the UI components offered by the CSV datasource plugin do not allow for such an integration (tested with Grafana v9.4.3 and marcusolsson-csv-datasource @ 0.6.3)

Is there any way to get relevant legend values with a CSV datasource?
```[tasklist]
### Tasks
```

**Comment by zoltanbedi** [comment]
filtering the data by time is not supported
