### ISSUE TITLE
Fields parsing not working as expected

### ISSUE THREAD

**Issue by LudwigJan** [grafana/grafana-csv-datasource#246]
Querying a csv file with this plugin works as expected.

However, when I try to use the fields tab for parsing the columns, it does not work.

The data looks like this:
![Screenshot 2023-08-30 at 13 11 13](https://github.com/grafana/grafana-csv-datasource/assets/129760848/2a274cf9-c77f-4f76-9b77-99e20c4ee293)

Now I want to parse the "Date (CET)" column to Time and the "SSP (BMRS)" column to Number.
![Screenshot 2023-08-30 at 13 09 05](https://github.com/grafana/grafana-csv-datasource/assets/129760848/ba1f9a14-b3d0-4dd4-b772-89996b28be19)

After doing so nothing happens and even if I save the dashboard, the content of the two field cells just disappears.
![Screenshot 2023-08-30 at 13 25 07](https://github.com/grafana/grafana-csv-datasource/assets/129760848/53043891-8e13-4814-b0f4-e8e904633d35)

I also tried putting them in like strings ("Date (CET)" and "SSP (BMRS)") which did not work.

Last thing I tried was skipping the first two columns and deactivating the "Header" toggle to just use the generic column names as explained in the documentation ("Field 1", "Field 2", ...). This also did not lead to the columns being parsed.

At the moment, I am using the grafana transformation (Convert field type) to get the numeric values but this is not the solution I am looking for, because it leads to NaN values in the original csv being replaced with 0.

Please let me know how to resolve that issue.
Best

**Comment by zoltanbedi** [comment]
Hey @LudwigJan, Can you please provide us the csv file so we can investigate this?

**Comment by gabor** [comment]
as we got no response we are closing the issue. we will reopen it if we receive new info.
