### ISSUE TITLE
The user name or password is incorrect.

### ISSUE THREAD

**Issue by fuba7771** [grafana/grafana-csv-datasource#271]
I get an error message "The user name or password is incorrect." when trying to define a network-path.

Grafana:             10.1.4
Plugin Version:   0.6.8
Grafana Host:   Windows Server 2019

example path:   //file-server.lan.test.de/files

Do i have to define some securities to share? Note, that the server, where grafana is installed, is under another domain (grafana.lan.server.de) . But if i open the share in Windows Server session it works without problems. Do i have to run Grafana as a user, that has access to that share? Currently Grafana is running under "System".

**Comment by zoltanbedi** [comment]
Sorry but I have no experience with this. You better ask this question in stackoverflow
