### ISSUE TITLE
Configurable default column type

### ISSUE THREAD

**Issue by anerg** [grafana/grafana-csv-datasource#274]
I'm using the plugin to fetch timeseries data from a HTTP API.  I've made a variable from metrics I request from the API and those are returned as columns in a csv.  

However, in order to plot them as timelines, I need to explicitly set type for all metrics that I can possibly fetch from the api (about 300 metrics), in every widget that I use to plot graphs. This makes it not possible to use unfortunately.

Being able to set "number" as default column type (and overriding the other 2-3 columns that are not numbers) would solve my problem.  Or being able to define a type with regexp and not only explicit column names.

<img width="1741" alt="image" src="https://github.com/grafana/grafana-csv-datasource/assets/2535615/747395b5-e47a-4b25-9503-17b1e8abd9eb">

**Comment by alpkahvecioglu** [comment]
I have the same issue and would love to see this implemented 👍

**Comment by yesoreyeram** [comment]
Hiya. As we are planning to deprecate this plugin, we are neither adding this feature nor investigating further. Sorry about that.

I would recommend to try [infinity datasource plugin](https://grafana.com/grafana/plugins/yesoreyeram-infinity-datasource/) instead.
