### ISSUE TITLE
Filtering reset when resizing column

### ISSUE THREAD

**Issue by rschitz** [grafana/grafana-csv-datasource#281]
Reproduced on the latest version of the plugin.
![NVIDIA_Share_h9A36ZVfYV](https://github.com/grafana/grafana-csv-datasource/assets/8385646/72f70dc2-6e8a-48ce-bbab-fef740468a64)

**Comment by zoltanbedi** [comment]
This is not related to csv datasource and was fixed back in Grafana 9. https://github.com/grafana/grafana/pull/48421

**Comment by rschitz** [comment]
thanks
