### ISSUE TITLE
CSV data in a table panel: Message: record on line 2: wrong number of fields

### ISSUE THREAD

**Issue by lakshay2711** [grafana/grafana-csv-datasource#282]
Hi,

I am facing some issues while reading data from csv. Below is a simple csv file data which I am trying to read in grafana.
But it is giving error `"record on line 2: wrong number of fields"`

![image](https://github.com/grafana/grafana-csv-datasource/assets/44000339/003f5a14-f92b-4502-bb0f-50c505da06dc)

Can you please let me know what is going wrong?

Regards

**Comment by lakshay2711** [comment]
Any updates on this issue ?

**Comment by zoltanbedi** [comment]
> Can you please let me know what is going wrong?

Your csv has wrong number of fields in the second row.

Can you send the csv that you see this error? @lakshay2711

**Comment by zoltanbedi** [comment]
I guess you figured it out yourself.
