### ISSUE TITLE
Multi line time-series

### ISSUE THREAD

**Issue by Wilmir** [grafana/grafana-csv-datasource#290]
I have a CSV file with the following fields.

timestamp, server, query_count.

How do I set up grafana so that i'll have a line chart for every server in one panel?

**Comment by gabor** [comment]
hi @Wilmir , the following should work:
- make sure that the `timestamp` field is marked as `type=time`, and the `query_count` field is marked as `type=number`.
- add a `Transform` to  the query, choose the `Prepare time series` transform. configure the prepare-time-series transform to use the `format=multi-frame time series`

<img width="469" alt="long" src="https://github.com/grafana/grafana-csv-datasource/assets/51989/817c10d1-e770-4ebc-b3b4-1f04e00a1547">


this should solve the problem. if it does not, please reply back and we can reopen the issue.
