### ISSUE TITLE
CSV file's UTF8 BOM header is part of first field name

### ISSUE THREAD

**Issue by gnaish** [grafana/grafana-csv-datasource#292]
If a CSV file contains the UTF8 BOM header - `EF BB BF` as the first 3 bytes of the file, it will be read as part of the first field name by the CSV plugin, which causes failed to select the first field in the Query Editor.  This is assuming the first line of the csv file is the row header. 

I could reproduce the issue on the latest plugin version 0.6.12, and Grafana version is on 8.5.4.

**Comment by zoltanbedi** [comment]
Hi @gnaish,
can you please provide a file that I can reproduce this with? Also if you can try it out with https://grafana.com/docs/plugins/yesoreyeram-infinity-datasource/latest/ and let us know how that goes would be awesome.

**Comment by yesoreyeram** [comment]
Hi @gnaish - Sorry you are having trouble with BOM headers in the CSV. As suggested by Zoltan, can you try this with Infinity plugin? ( Infinity plugin [already have support](https://github.com/grafana/grafana-infinity-datasource/blob/8547209d10d9b41d13d5e682036692dde2177ff4/pkg/infinity/client.go#L231) for removing BOM headers. If that is not working for you, can you create a github issue [there](https://github.com/grafana/grafana-infinity-datasource/issues/new/choose)?

**Note**: To unify the JSON/CSV/XML datasource plugins, we are **planning to deprecate** this plugin in favour of [Infinity datasource plugin](https://grafana.com/grafana/plugins/yesoreyeram-infinity-datasource/) which is actively maintained by Grafana. When using Infinity plugin, suggest to use its backend parser which have support for more grafana native options such as alerting, recorded queries, public dashboards.

**Comment by gnaish** [comment]
Thanks for the heads up and really appreciate for your efforts to develop this great plugin. 

We will explore Infinity datasource plugin.
