### ISSUE TITLE
Illegal Instruction on Raspberry Pi Zero

### ISSUE THREAD

**Issue by kirpalricky** [grafana/grafana-csv-datasource#293]
The issue seems to be happening for executable file gpx_csv-datasource_linux_arm probably because of some incorrect flags used during compliation as I was able to compile a working executable using GOOS=linux GOARCH=ARM GOARM=6

But given the signature has changed I am unable to load the new executable, so request support in fixing the issue as it would help others in installing this necessary plugin in a workable fashion.

**Comment by gabor** [comment]
hi @kirpalricky thank you for looking into this issue. the default-behavior of the grafana plugin build system currently builds with flags that (as you found out)  does not support hte raspberry pi zero.

as you were able to build a binary that works for you, there are two ways to make the custom binary to run in grafana:
1. you can use this grafana setting to allow loading an unsigned plugin: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#allow_loading_unsigned_plugins (the usual this-lowers-security warnings apply)
2. you can sign a private plugin ( https://grafana.com/developers/plugin-tools/publish-a-plugin/sign-a-plugin#sign-a-private-plugin )

i hope this helps.

**Comment by kirpalricky** [comment]
Thanks for the comment. I was able to sign the plugin and use it.
