### ISSUE TITLE
CSV datasource Variables 

### ISSUE THREAD

**Issue by yocaning** [grafana/grafana-csv-datasource#30]
when i use CSV datasource to set some variables，it does not work

**Comment by yocaning** [comment]
the query does not work

**Comment by yocaning** [comment]
Does it support this feature （set cariables by csv datasource）

**Comment by marcusolsson** [comment]
Variables queries are currently not supported, but would be a nice improvement :)

**Comment by yocaning** [comment]
thank you for your reply，looking forward to this feature 。

**Comment by yocaning** [comment]
> Variables queries are currently not supported, but would be a nice improvement :)

thank you for your reply，looking forward to this feature 。

**Comment by marcusolsson** [comment]
I've added the support for variables query. Will be included in the next version.
