### ISSUE TITLE
Error  context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by WiG96** [grafana/grafana-csv-datasource#306]
59089728a21a:/usr/share/grafana/bin$ grafana-cli plugins install marcusolsson-csv-datasource

Deprecation warning: The standalone 'grafana-cli' program is deprecated and will be removed in the future. Please update all uses of 'grafana-cli' to 'grafana cli'

Error: ✗ Get "https://grafana.com/api/plugins/marcusolsson-csv-datasource/versions": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
59089728a21a:/usr/share/grafana/bin$ grafana cli plugins install marcusolsson-csv-datasource

**Comment by zoltanbedi** [comment]
This is not a problem in the plugin but in somewhere else. Maybe the server was down when you tried to install the plugin or you have some firewall that prevented it.
