### ISSUE TITLE
Create a dropdown menu with the headers of the csv

### ISSUE THREAD

**Issue by oserresb** [grafana/grafana-csv-datasource#312]
Hi,

I would like to implement a modification, I don't know if it's possible but It could be a good improvement.
My idea is when you add a new field, to select it, create a dropdown menu getting the headers of the csv instead of write it.
I'm thinking on it because I manage CSV with 90 columns and it would be more friendly with this improvement.
I don't know if you could provide me help to do this

**Comment by zoltanbedi** [comment]
Hi @oserresb,
Sorry we are not accepting feature requests or PRs for this plugin anymore. We advise you to use https://github.com/grafana/grafana-infinity-datasource.
