### ISSUE TITLE
plugin setting seems useless for local mode

### ISSUE THREAD

**Issue by EnderAvaritia** [grafana/grafana-csv-datasource#316]
I modified the config and restrart
![Snipaste_2024-08-05_17-39-52](https://github.com/user-attachments/assets/65fee9dd-e698-48ca-af56-092180ee19bc)
but useless
![Snipaste_2024-08-05_17-42-19](https://github.com/user-attachments/assets/11cb7ac1-a12f-4031-87dc-18b4308a5eed)

**Comment by yesoreyeram** [comment]
Can you make sure to have the process runnning grafana / the plugin have read access to the file.

**Comment by EnderAvaritia** [comment]
> Can you make sure to have the process runnning grafana / the plugin have read access to the file.

I an not sure , i use the docker and mount the dictory as the introduction 

I will try to test the process next time i use it
