### ISSUE TITLE
Plugin disabled by Grafana

### ISSUE THREAD

**Issue by drano02** [grafana/grafana-csv-datasource#32]
Just installed Grafana 7.4.0. Installed plugin. Shows disabled because of "Modified signature":

We have encountered data source backend plugins that are unsigned. Grafana Labs cannot guarantee the integrity of unsigned plugins and recommends using signed plugins only.
The following plugins are disabled and not shown in the list below:

    marcusolsson-csv-datasource

    Modified signature - Valid signature but content has been modified

Note that unsigned front-end datasource plugins are still usable, but this is subject to change in the upcoming releases of Grafana

**Comment by marcusolsson** [comment]
Thank you for noticing. I'll look into this right away.

**Comment by marcusolsson** [comment]
I've just tested version 0.3.3 in both 7.3.7 and 7.4.0 and it shows a valid signature.

What OS are you running, and how did you install the plugin?

**Comment by drano02** [comment]
I am using Windows 10 with all the latest updates:
Edition: Windows 10 Pro
Version: 20H2
OS Build: 19042.746

Installation:

C:\Users\drano>grafana-cli plugins install marcusolsson-csv-datasource
installing marcusolsson-csv-datasource @ 0.3.3
from:
https://grafana.com/api/plugins/marcusolsson-csv-datasource/versions/0.3.3/download
into: ../data/plugins

←[32m✔←[0m Installed marcusolsson-csv-datasource successfully
Failed to remove temporary
filefileC:\Users\drano\AppData\Local\Temp\954340319.ziperrremove
C:\Users\drano\AppData\Local\Temp\954340319.zip: The process cannot access
the file because it is being used by another process.
Restart grafana after installing plugins . <service grafana-server restart>


C:\Users\drano>

**Comment by marcusolsson** [comment]
Thank you for the details, I'll see if I can get my hands on a Windows machine to try and reproduce this.

**Comment by marcusolsson** [comment]
Just to confirm, are you able to install the plugin on 7.3?

**Comment by marcusolsson** [comment]
I've verified that the plugin works on 7.3.7, but fails in 7.4 on Windows 10. This feels like a bug in Grafana. I'll do some more research and get back to you.

**Comment by drano02** [comment]
Yes, I actually did install it on Grafana 7.3 but did not try it. I got a
message saying Grafana could be upgraded, which I did. Then, I noticed the
problem.

**Comment by drano02** [comment]
FYI. I went back to Grafana 7.37 and reinstalled your plugin okay. I wanted
to use it with a local CSV file which works if I enter file name, rather
than full path in the Path item of the UI. Then, the CSV file must be
placed in the "Grafana Home" folder. That will certainly take care of me
for now.

Thanks for your help!

Norm

**Comment by marcusolsson** [comment]
There's bug related to paths on Windows. If you use forward-slashes instead, you can use a full path. But I'm glad you got it to work.

https://github.com/marcusolsson/grafana-csv-datasource/issues/26

The Grafana team is working on a fix, so try again when the next release is out :)

**Comment by k8s-jp** [comment]
level=error msg="Plugin validation failed" pluginId=larona-epict-panel error="plugin 'larona-epict-panel' has an modified signature"

I have built a docker image using my plugins and i ftecjed plugins from docker image it worked fine for grafana version 8 but for grafana 11 i am facing the above error.
Any suggestions
