### ISSUE TITLE
CSV plugin (above 0.1.0) not working if file is hosted in IIS

### ISSUE THREAD

**Issue by G0nz0uk** [grafana/grafana-csv-datasource#34]
Hello,

As requested, there seems to be an issue with this plugin if it's on a version greater than 0.1.0 if the csv is hosted in IIS.

Please read https://github.com/marcusolsson/grafana-csv-datasource/discussions/31

If I'm on 0.1.0 all works fine, if I upgrade to 0.3.3 they stop working.  If I run locally, in Gish, on a Python Website all works, it's just IIS.

Thanks

**Comment by G0nz0uk** [comment]
Hello Marcus, is there anymore testing I can do for you on this?

**Comment by marcusolsson** [comment]
Unfortunately, I'm out of guesses on this :( I'm hoping that another Windows user can reproduce this to be honest.

**Comment by G0nz0uk** [comment]
I’m thinking the only way round it is if I script the CSVs so they get copied from all the Window servers to a folder on Linux Grafana server and use the local data source option instead.

**Comment by micha06de** [comment]
> 
> 
> Unfortunately, I'm out of guesses on this :( I'm hoping that another Windows user can reproduce this to be honest.

Yes the problem occurs and has cost me hours. :(
If "tab" is entered as delimiter, the following output appears:

```
Table
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>406 - Clientbrowser akzeptiert den MIME-Typ der angeforderten Seite nicht.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
...
```

**Comment by G0nz0uk** [comment]
I scripted all CSVs to go from our Windows servers to the Grafana Ubuntu server and upgraded it and used the local option instead, all good now.

Using: 
CSV 0.3.3
Grafana 7.4.3

**Comment by marcusolsson** [comment]
@micha06de It sounds like your issue is more related to an incorrect query (although the lack of debugging support made it hard to track down) rather than IIS?

Closing this as it seems like this is no longer an issue. Let me know if not and I'll reopen.
