### ISSUE TITLE
Plugin Health Check Failed

### ISSUE THREAD

**Issue by Heinzler** [grafana/grafana-csv-datasource#4]
I always get the error "Plugin Health Check Failed" with my own CSV file as well as with your example file from the other case

**Comment by marcusolsson** [comment]
Hm. I'll look into this, but it sounds like it could be a network issue then? Could you open the browser DevTools to get more information about the failing request?

**Comment by Heinzler** [comment]
But the File is on the same machine and I tried with IP and localhost. Could it be a problem with ARM or Encoding? I‘m using Grafana 7.3.4 on Raspberry Pi. What do I have to look for in DevTools?

**Comment by Heinzler** [comment]
Status of GET 	http://IP:3000/api/datasources/3/health is 500 Internal Server Error
updated to grafana 7.3.5, same Result

**Comment by marcusolsson** [comment]
Unfortunately, the plugin doesn't yet support local files. I'll make sure to add it to the README for clarification. I've also [created an issue](https://github.com/marcusolsson/grafana-csv-datasource/issues/6) to discuss local file support.

**Comment by Heinzler** [comment]
The file is on the same device but is not accessed locally but is published via Apache. Does this not work?

**Comment by marcusolsson** [comment]
That should work. I'll be able to debug this more the coming week. I think I have enough information to reproduce this. Thanks!

**Comment by marcusolsson** [comment]
I've just published [v0.2.0](https://grafana.com/grafana/plugins/marcusolsson-csv-datasource?version=0.2.0) which adds initial support for local CSV files, in case you can't get it to work with Apache.

**Comment by mdax82** [comment]
Thx for the plugin :)

Tested v0.2.0 

Always end up in "Plugin health check failed"

Using it then with local
`POST https://foobar:3000/api/ds/query 500 (Internal Server Error)`

the format for the file is
/my/path/to.file

Thats right format? Unix permission granted to all...

Same Error for the test file ime_series_covid19_confirmed_global.csv via http - seems there is something odd access the DS?

**Comment by Heinzler** [comment]
with version 0.3.0 it works, thanks

**Comment by mdax82** [comment]
looks good with 0.3.0 thanks!

**Comment by simonmichael** [comment]
It doesn't work for me (version 0.3.3). Should a simple absolute file path like `/path/to/file.csv` work ? With grafana debug logging enabled, I see:

```
t=2021-02-17T15:39:22-0800 lvl=dbug msg="Received command to update data source" logger=datasources url=/path/to/file.csv
t=2021-02-17T15:39:22-0800 lvl=dbug msg="Applying default URL parsing for this data source type" logger=datasource type=marcusolsson-csv-datasource url=/path/to/file.csv
t=2021-02-17T15:39:22-0800 lvl=dbug msg="Data source URL doesn't specify protocol, so prepending it with http:// in order to make it unambiguous" logger=datasource type=marcusolsson-csv-datasource url=/path/to/file.csv
t=2021-02-17T15:39:22-0800 lvl=dbug msg="Not adding CSP header to response since it's disabled" logger=http.server
t=2021-02-17T15:39:22-0800 lvl=dbug msg="Not adding CSP header to response since it's disabled" logger=http.server
t=2021-02-17T15:39:22-0800 lvl=dbug msg="Not adding CSP header to response since it's disabled" logger=http.server
t=2021-02-17T15:39:22-0800 lvl=dbug msg="Querying for data source via SQL store" logger=datasources id=1 orgId=1
t=2021-02-17T15:39:22-0800 lvl=eror msg="Plugin health check failed" logger=context userId=1 orgId=1 uname=admin error="failed to check plugin health: health check failed" remote_addr=[::1]
```

If I add `file://`, I see:

```
t=2021-02-17T15:39:57-0800 lvl=dbug msg="Received command to update data source" logger=datasources url=file://path/to/file.csv
t=2021-02-17T15:39:57-0800 lvl=dbug msg="Applying default URL parsing for this data source type" logger=datasource type=marcusolsson-csv-datasource url=file://path/to/file.csv
t=2021-02-17T15:39:57-0800 lvl=dbug msg="Not adding CSP header to response since it's disabled" logger=http.server
t=2021-02-17T15:39:57-0800 lvl=dbug msg="Not adding CSP header to response since it's disabled" logger=http.server
t=2021-02-17T15:39:57-0800 lvl=dbug msg="Not adding CSP header to response since it's disabled" logger=http.server
t=2021-02-17T15:39:57-0800 lvl=dbug msg="Querying for data source via SQL store" logger=datasources id=1 orgId=1
t=2021-02-17T15:39:57-0800 lvl=eror msg="Plugin health check failed" logger=context userId=1 orgId=1 uname=admin error="failed to check plugin health: health check failed" remote_addr=[::1]
```

(Neither the http: nor file: urls works in Safari, are they required to ?)

**Comment by marcusolsson** [comment]
@simonmichael Another user has run into the same issue it seems, I've created https://github.com/marcusolsson/grafana-csv-datasource/issues/37 where we can try tracking this down.
