### ISSUE TITLE
Support for converting commas to dots in values

### ISSUE THREAD

**Issue by Weltherrscher** [grafana/grafana-csv-datasource#43]
It would be nice if one could select the decimal delimiter in the data source settings.
In Germany some COVID-Tables are filled with numbers like 45,67.
Grafana cannot interpret these values as numbers, only as strings.
Thus its impossible to color the values. =(

**Comment by marcusolsson** [comment]
Thank you for reporting this! I agree that we should support this. I'm not sure when I can start working on it though. 

In general, I prioritize the issues with the most votes so if this matters to you, please add your vote. If someone wants to work on this, I'd be happy to help!

**Comment by Weltherrscher** [comment]
Its nice to have, but has no priority, displaying the values works great anyway even without coloring. =)

**Comment by micha06de** [comment]
Workaround: You can use sed and regexp to replace the commas with the dots.

**Comment by Weltherrscher** [comment]
How could i do that within the stream of the plugin?
The data source is an URL, I have no possibility to use sed between downloading from the csv plugin and the query?
