### ISSUE TITLE
Date parsing failing with some "interestingly" formatted date values

### ISSUE THREAD

**Issue by p4block** [grafana/grafana-csv-datasource#44]
I was having gaps in my charts and quickly found the culprit using the table view

Viewing as string
![image](https://user-images.githubusercontent.com/5960575/109387680-2787b500-7903-11eb-8d2e-849e301233dd.png)

Viewing as time
![image](https://user-images.githubusercontent.com/5960575/109387686-2fdff000-7903-11eb-9f13-f4ab0608e996.png)

The original format is arguably pretty bad, however, Grafana itself via the override date format understands it no problem, but the plugin Time type does not.

**Comment by marcusolsson** [comment]
Unfortunately, we can't use the same function for parsing time as Grafana does, since the plugin is parsing the CSV on the backend (with Go), rather than in the browser (with TypeScript). That being said, I've added your format to the list of supported formats. Thanks for reporting this! 👍

**Comment by p4block** [comment]
Thanks a lot for the quick fix, this has made my day (and weekend) 

I'm now able to replace our huge and messy custom javascript charts page with a Grafana dashboard in no time :smile:

**Comment by p4block** [comment]
I just tried v.0.4.0 (thanks again for the quick response) and found it's still not parsing them correctly. 

For reference [this](https://marmenor.upct.es/thredds/fileServer/L4/Temperatura.csv) is my csv file. Behavior seems the same as with the old pre-fix version. I also wonder where it's getting the "hour" from as it only has a date.

**Comment by marcusolsson** [comment]
It seems like your data set contains mixed formats, which leads to the "wrong" format being detected. I've changed the order of the layouts to that it tries the single digit version first, which seems to work. Could you try v0.4.1?

Since the date is parsed server-side, the plugin defaults to UTC when there's no time zone information. When displaying the time in the browser, it displays the time in the time zone of the dashboard/browser, which leads to the added hour.

**Comment by p4block** [comment]
That did it. Thanks a million :smile: 

Due to... issues the file has to stay "broken" as it is right now until I've worked a few quirks, it definitely shouldn't have had 2 date formats inside in the first place. May this help other unfortunate people in the future.
