### ISSUE TITLE
Data not updating

### ISSUE THREAD

**Issue by MurphySunset** [grafana/grafana-csv-datasource#45]
Hello there,

I'm quite uncomfortable posting an issue for something that might not be... Data is not updating for me. Eventhough my source CSV changes, nothing changes in the dashboard. Is the plugin downloading the target file on each refresh ? Or does he download the file just once and then only display the cached file ?

Thank you.

Regards,

Baptiste

**Comment by marcusolsson** [comment]
Hi, and thank you for taking the time to report your experience ❤️ 

I did a quick test of hosting a file on a file server, querying it, changing it, and then querying it again. It does seems to work for me. The plugin doesn't cache any requests. You should be getting the current data on each refresh.

Are you able to curl the endpoint and verify that it has indeed been updated?

**Comment by MurphySunset** [comment]
Thank you for that fast answer @marcusolsson. Curl (in the docker container) is showing old data so the problem is not on the side of the plugin. What's weird is that from my place I have the up to date data... I'll look into it. Sorry for disturbing you!

**Comment by marcusolsson** [comment]
No worries at all. Thanks for trying out the plugin!
