### ISSUE TITLE
Custom http headers do not work yet

### ISSUE THREAD

**Issue by rseidt** [grafana/grafana-csv-datasource#5]
I'm keen on trying out the csv data source in grafana as I have an endpoint which can produce csv data if you add the 
```http
Accept: text/csv
```
http header. (If the header is missing it complains)

As of the moment the plugin seem to ignore the custom header section in the config, it might be an option to add the mime type text/csv as a default to the performed http request, as this anyway might always be the expected mime type for this plugin.

**Comment by marcusolsson** [comment]
Thanks for reporting! The plugin should have support for custom headers, so this looks like a bug.

**Comment by medicinemann** [comment]
I have the same issue. I'm trying to read csv data from Thingspeak. It works fine with a public channel, for example https://thingspeak.com/channels/624218/feed.csv, but I need to read from a private channel XXXXX with an api_key header YYYYYYYYYY like so: https://thingspeak.com/channels/XXXXXX/feed.csv?api_key=YYYYYYYYYY&days=1. I tried to enter https://thingspeak.com/channels/XXXXXX/feed.csv as the URL and api_key=YYYYYYYYYY&days=1 as "Custom query parameters" under "Misc", but I get an error and no data back. 

<img width="1202" alt="billede" src="https://user-images.githubusercontent.com/76555408/103082364-3471ea80-45da-11eb-8983-6fbcdde633bd.png">

I also tried to add the api_key and days as custom HTTP headers but this also gives the same error.

<img width="643" alt="billede" src="https://user-images.githubusercontent.com/76555408/103082245-ed83f500-45d9-11eb-8c8c-49a1f670ea99.png">

**Comment by marcusolsson** [comment]
Thank you @medicinemann for the detailed bug report! I'll try to get working on this ASAP

**Comment by marcusolsson** [comment]
It seems like the custom query parameters aren't added to the health check (when clicking Save & Test). If I ignore the error on the data source config and make a query, the query parameters are present.

I'll look into why they aren't passed for the health check. In the meantime, could you check and see if the query works outside of the data source config page?

**Comment by medicinemann** [comment]
I have only tried it on grafana.com, not on a local install, and I get no data from my query. I can try it on a local install but maybe not today though.

**Comment by medicinemann** [comment]
I tried it now on a fresh local install of grafana v7.3.6 and now I can't even get the public channel query to work. I installed the plugin using the CLI `sudo -u grafana grafana-cli plugins install marcusolsson-csv-datasource`
 It fails the plugin health check, and when I save the data source anyway and try to use it in grafana I get this error:

<img width="1196" alt="Screenshot 2020-12-30 at 19 32 34" src="https://user-images.githubusercontent.com/76555408/103373681-dfe8d680-4ad5-11eb-9f17-7fc67aff66b8.png">

The csv data returned by Thingspeak when using https://thingspeak.com/channels/624218/feed.csv looks like this:


created_at,entry_id,field1,field2
2020-12-30 14:28:24 +0100,188179,19120,125
2020-12-30 14:28:27 +0100,188180,19121,125
2020-12-30 14:28:32 +0100,188181,19122,125
2020-12-30 14:28:35 +0100,188182,19123,125
2020-12-30 15:05:54 +0100,188183,19124,125
2020-12-30 15:06:58 +0100,188184,19124,20

**Comment by marcusolsson** [comment]
I've published [v0.2.0](https://grafana.com/grafana/plugins/marcusolsson-csv-datasource?version=0.2.0) which adds the Accept header by default. I've also added tests to verify that custom headers are indeed passed. Could you please try the latest version and see if the problem persists?

**Comment by medicinemann** [comment]
It works perfectly now! Both with public and private Thingspeak channels when I add the api key to the "Custom query parameters"! Thank you so much for fixing this!

**Comment by rseidt** [comment]
@marcusolsson I'd like to pull this out again after finding some time to restest and upgrading to v 0.3.0:
- default accept header works. accept text/csv is added to the request
but all other custom http headers I configure in the configuration are still not snt to the data source:

See the config where I configured a custom Header:
![image](https://user-images.githubusercontent.com/46084345/104600961-f5cfcd00-5679-11eb-9ba1-b19a3328b582.png)

See the result in the requestbin:
![image](https://user-images.githubusercontent.com/46084345/104601054-10a24180-567a-11eb-934b-31e28980bc99.png)

The Expected result is, that beside the accept text/csv header there should now be an X-Header:

```http
X-Test-123: Value123
```
