### ISSUE TITLE
Minified React error #130; generated when selecting "configuration >datasources>CSV>local instead of http

### ISSUE THREAD

**Issue by blivingston-managerplus** [grafana/grafana-csv-datasource#54]
Windows server 2019 Datacenter Version 1809, OS build  17763.1817.
grafana-csv-datasource-0.41
Downloaded plugin as zip file, installed in plugins, restarted server.

Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

    in Unknown
    in div
    in t
    in form
    in div
    in div
    in t
    in div
    in div
    in div
    in t
    in t
    in div
    in t
    in t
    in x
    in ConnectWithCleanUp(Connect(t))
    in r
    in Unknown
    in t
    in Unknown
    in h
    in Unknown
    in Unknown
    in t
    in t
    in l

**Comment by marcusolsson** [comment]
`Error: Minified React error` typically means that the plugin is using features that aren't available in the version of Grafana you're running. The CSV plugin requires at least Grafana 7.3.

**Comment by blivingston-managerplus** [comment]
You are correct, updating resolved the issue. Thanks!

**Comment by marcusolsson** [comment]
I've added a [Troubleshooting](https://marcus.se.net/grafana-json-datasource/troubleshooting) page to the docs site to hopefully help other with the same problem.
