### ISSUE TITLE
record on line 3: wrong number of fields

### ISSUE THREAD

**Issue by bicaluv** [grafana/grafana-csv-datasource#56]
Hi!
I'm tying to "Explore" my very simple csv file using this Dropbox URL: https://www.dropbox.com/s/xqprwqdu6z25uy4/temp.csv?dl=0
While creating the Data Source with the given URL, it says that everything is fine and tested.
But when calling "Explore", the only thing I get is 
`record on line 3: wrong number of fields`

**Comment by marcusolsson** [comment]
The plugin uses the first line to detect the number of fields/columns. I suspect that the blank header for the first column is messing things up here. Could you try to remove the first column and try again?

**Comment by bicaluv** [comment]
What do you mean by "blank header for the first column"?
Current content of the file looks like this:
```
date,name,cpu,gpu
04/15/2021,test,45,46
```
I do not see any blank header.

**Comment by marcusolsson** [comment]
Oh sorry, I don't have Dropbox, and in the web preview it appears to have added an extra column for line numbers. I tried to reproduce the issue with the data you provided, but it seems to work for me.

What version of the plugin and Grafana are you running?

<img width="761" alt="Screenshot 2021-04-17 at 15 53 05@2x" src="https://user-images.githubusercontent.com/8396880/115115499-0ce1cc00-9f95-11eb-9296-0cf532f98185.png">

**Comment by bicaluv** [comment]
Tanks for having a look on it.
I use the Grafana cloud version 7.3.0 with the csv plug-in 0.4.1

Maybe Dropbox is causing the issue, even when using https://www.dropbox.com/s/xqprwqdu6z25uy4/temp.csv?raw=1 which should fore Dropbox to present the file without any rendering.

BTW: even without an Dropbox account you should be able the use the provided link.

**Comment by marcusolsson** [comment]
I used the Dropbox URL you provided to create a new data source on 7.3.0, but I'm unfortunately not able to reproduce the error you're seeing. Could it be related to connection details, or template variables?

**Comment by bicaluv** [comment]
As for the data source I kept everything as default.
And here's how I use the Explore:
![image](https://user-images.githubusercontent.com/17777937/115155460-58bd6f80-a080-11eb-908a-649d52769c7e.png)

Is there any additional logging I can activate?

**Comment by dflorian** [comment]
@bicaluv did you unselect the TLS verify?

![Screen Shot 2021-04-21 at 7 01 52 PM](https://user-images.githubusercontent.com/15654298/115631623-2d32c300-a2d4-11eb-9d3f-42ce7ffaac29.png)

That made it work on my end for GCS

**Comment by bicaluv** [comment]
Nope, still didn't change anything.
URL I currently use: https://www.dropbox.com/s/xqprwqdu6z25uy4/temp.csv?raw=1
Really too strange. Added data source again and now I am not able to call Explore anymore. Simply get the black page without anything.

**Comment by akosiaris** [comment]
Hi! 

First off, thanks for this plugin. It looks very promising!

Now to the issue at hand, I face this as well . I think #64 is also related (or at least up to now the error is exactly the same). 

My grafana version is `7.5.5` and plugin version is `0.4.1`

I tried to load https://opendata.ecdc.europa.eu/covid19/vaccine_tracker/csv/data.csv and I get `record on line 8: wrong number of fields`

Fetching the csv with curl and passing it through python CSV reader, everything looks fine. I 've checked `Skip TLS Verify` but it makes no difference. 

This happens on a newly setup dashboard, with a single panel added. The error itself is being returned by grafana when a request to `api/ds/query` and the response from grafana is 

```
{"results":{"A":{"error":"record on line 8: wrong number of fields","refId":"A","series":null,"tables":null,"dataframes":[]}},"message":"record on line 8: wrong number of fields"}
```

Fetching the CSV file via curl and putting on the filesystem and then instructing the data source to load it locally works just fine. Which tells me the error has something to do with the HTTP(S) fetching of the CSV file.

I should mention that the gas prices CSV loads just fine.

**Comment by marcusolsson** [comment]
I've found the issue causing this. The plugin is adding `Accept: text/csv` to the HTTP header, which is not supported by some servers. If I remove it, https://opendata.ecdc.europa.eu/covid19/vaccine_tracker/csv/data.csv works, otherwise I'm getting a 406 from the server.

Since you can add you own headers with the new and improved query editor, I think it's safe to remove the default one.

**Comment by akosiaris** [comment]
Can confirm it works fine in 8.0.0-beta2. Many thanks again!

**Comment by bicaluv** [comment]
I really would give it a try, but do not how to update the already installed CSV plugin in Gravana cloud conf.
Gravana tells me "grafana-cli plugins update marcusolsson-csv-datasource" but how do I do this in cloud env?

Managed to get version 0.5.0 installed, but still get the error when trying to "Explore" with data from https://www.dropbox.com/s/xqprwqdu6z25uy4/temp.csv?raw=1

Edit: Made it work by explicit adding the "raw=1" as param in the explore query.
