### ISSUE TITLE
feature request: custom parameters

### ISSUE THREAD

**Issue by gdassori** [grafana/grafana-csv-datasource#59]
Feature Request: Add support for custom parameters in the panel configuration.
Thanks!

**Comment by marcusolsson** [comment]
I'm planning to bring the tabbed editor from the JSON API data source over to this plugin. Would that work for you?

**Comment by gdassori** [comment]
Hi @marcusolsson , that's fun, you just commented when I was here to enrich the issue.

Core feature: 

A "params" configuration dialog, as in the JSON API data source plugin, yes.

[image](https://user-images.githubusercontent.com/5659270/116048961-0b3f9480-a676-11eb-9f34-1db5040b2217.png)

Nice to have:

- An option into the data source configuration, to use all the dashboard's variables in querystring by default, without having to populate the Params key:value tab.

**Comment by marcusolsson** [comment]
I think this could be a nice addition to the plugin, though since it's already possible to manually add dashboard variables as params (although cumbersome) I'm putting a low priority on this for now.

**Comment by marcusolsson** [comment]
Fixed in https://github.com/marcusolsson/grafana-csv-datasource/commit/505f8f6450cdb0cf08b7f4faaf7478c5bbee7bc6
