### ISSUE TITLE
Error with covid sample

### ISSUE THREAD

**Issue by quan-nobl9** [grafana/grafana-csv-datasource#64]
Just tried the plugin with the covid test dataset documented on the front page.

After loading the dataset and going to "Explore" in grafana, then selecting the data, the following error appears:

record on line 57: wrong number of fields

Not sure if there's a parsing issue or if the csv format is bad but wanted to share the error.
Note, loading the natural gas sample csv works.

**Comment by marcusolsson** [comment]
Sorry, the example in the README was wrong. You need to use the raw content rather than the GitHub file page. I've updated the README accordingly. Thanks!
