### ISSUE TITLE
Feature request: Regex support for field names

### ISSUE THREAD

**Issue by andrew-mcnaught** [grafana/grafana-csv-datasource#68]
Looking at the addition of selecting field names using regex (the example of /Bid/ giving all Bid* columns). This was covered in a little more detail on the discussion [here](https://github.com/marcusolsson/grafana-csv-datasource/discussions/66)

**Comment by marcusolsson** [comment]
This was released as a experimental feature in 0.5.0. Without feedback that would advise otherwise, this will be part of the next (0.6.0) release.

**Comment by andrew-mcnaught** [comment]
I have actually been using it and no complaints so far, working well for me! Thanks

**Comment by aboehm64** [comment]
thanks a lot for supporting my case.
I got it to work, and your regex support does it perfect for me.  :-)
