### ISSUE TITLE
Installation: Win10: where is the grafana plugins directory?

### ISSUE THREAD

**Issue by cpmitch** [grafana/grafana-csv-datasource#7]
Hello-

While running Grafana locally, via chrome browser, I would like to download the ZIP and install on my PC. Where exactly can I find my plugins directory, and where should I un-zip the file? Your instruction say:

Alternatively, you can manually download the .zip file and unpack it into your grafana plugins directory.

Thanks.

**Comment by CaptainKarma** [comment]
On Windows 10 here; C:\Program Files\GrafanaLabs\grafana\data\plugins

So you end up with the following structure;

C:\Program Files\GrafanaLabs\grafana\data\plugins\marcusolsson-csv-datasource

Then restart the Grafana service

**Comment by cpmitch** [comment]
Thank you @CaptainKarma that worked. Closing bug.
