### ISSUE TITLE
msg="Failed to start plugin" after update to 0.5.0

### ISSUE THREAD

**Issue by aboehm64** [grafana/grafana-csv-datasource#72]
I updated the marcusolsson-csv-datasource plugin to try to use the new regex support in the field names. 
After the update, the plugin does not start anymore. The error message is the following.

**May 28 08:10:19 linux-7x33.suse grafana-server[32040]: t=2021-05-28T08:10:19+0200 lvl=eror msg="Failed to start plugin" logger=plugins.backend pluginId=grafana-csv-plugin error="Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."**

What did I wrong, or what can I do to resolve this?
I tried to remove and re-add the plugin, but I got no change.  :-(
Thank you very much for supporting.

**Comment by marcusolsson** [comment]
Thanks for reporting this! 🙏  Can I ask what Grafana version you're running?

**Comment by aboehm64** [comment]
of course you can.  😊

my version is Grafana v7.5.7 (91de51771c).


________________________________
Von: Marcus Olsson ***@***.***>
Gesendet: Freitag, 28. Mai 2021 11:52
An: marcusolsson/grafana-csv-datasource
Cc: Boehm, Andreas; Author
Betreff: Re: [marcusolsson/grafana-csv-datasource] msg="Failed to start plugin" after update to 0.5.0 (#72)


Thanks for reporting this! 🙏 Can I ask what Grafana version you're running?

**Comment by aboehm64** [comment]
I did get the plugin run again. I removed all other non default plugins, including csv plugin, and added csv plugin afterwards.
now csv plugin is running again.  :-)
may I ask, if the regex support for the field names are already implemented, and how could it be used?
thanks for answering.

**Comment by aboehm64** [comment]
thanks a lot for supporting my case.
I got it to work, and your regex support does it perfect for me.  :-)

**Comment by marcusolsson** [comment]
Sorry for the late response here, but I'm happy to hear you got it working!
