### ISSUE TITLE
The handler is invalid

### ISSUE THREAD

**Issue by HenrikRolandHansen** [grafana/grafana-csv-datasource#75]
When using "path" the plugin keeps warning that the handler is invalid. The plugin returns data even with this warning.

![image](https://user-images.githubusercontent.com/8969659/120310471-b6c3b080-c2d6-11eb-9654-603b8082460b.png)

The data source returns Success.

![image](https://user-images.githubusercontent.com/8969659/120310591-d78c0600-c2d6-11eb-88cf-24f79b1c1d45.png)

**Comment by marcusolsson** [comment]
Unfortunately, I haven't had the chance to test this on Windows yet, but I suspect that it might be due to issues with the path delimiter. Though it's weird that you're getting a response _and_ error.

**Comment by HenrikRolandHansen** [comment]
Found the issue. I had a "B" query with no filename in the path so that fails.
