### ISSUE TITLE
Get " net/http: invalid header field name ""

### ISSUE THREAD

**Issue by ouinouin** [grafana/grafana-csv-datasource#9]
hi, 
got this issue while retrieving my csv
Get "http://192.168.10.239:12345/test.csv": net/http: invalid header field name ""
 my csv looks like : 
`Time,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,chaud Z1,chaud Z2,chaud Z3,froid Z1,froid Z2,froid Z3,regul Z1,regul Z2,regul Z3
2020-12-03 10:30:30,15.32,15.42,14.31,15.12,15.62,15.62,14.51,14.71,16.02,14.84,15.22,14.71,14.51,15.42,15.01,16.02,14.71,15.42,15.42,14.54,14.94,15.42,15.52,15.09,15.04,250.37,249.62,250.65,249.89,250.68,250.98,250.10,250.01,250.06
2020-12-03 10:30:35,15.32,15.42,14.31,15.12,15.62,15.62,14.61,14.71,16.02,14.84,15.22,14.71,14.51,15.42,15.01,16.02,14.71,15.42,15.42,14.54,14.84,15.42,15.52,15.09,14.94,250.37,249.62,250.66,249.89,250.67,250.97,250.10,250.02,250.05
2020-12-03 10:30:40,15.32,15.42,14.31,15.12,15.62,15.62,14.61,14.61,16.02,14.84,15.22,14.71,14.51,15.42,15.01,16.02,14.71,15.42,15.42,14.54,14.84,15.42,15.52,15.09,14.94,250.37,249.62,250.66,249.88,250.67,250.97,250.07,250.02,250.07
2020-12-03 10:30:45,15.32,15.42,14.31,15.12,15.62,15.62,14.61,14.61,16.02,14.84,15.32,14.71,14.51,15.42,15.01,16.02,14.71,15.42,15.42,14.54,14.84,15.42,15.52,15.09,14.94,250.37,249.62,250.66,249.88,250.67,250.98,250.04,250.02,250.07
`
meaning the dates are not in colums but in lines (as most of the CSV logging somethign does.
is your plugin able to withstand this kind of presentation ?

**Comment by marcusolsson** [comment]
Your CSV looks fine to me and should be supported. The error is coming from net/http, which leads me to believe it's a connectivity issue. Have you added any custom headers in your data source config?

**Comment by ouinouin** [comment]
hi, 
i re did the job on my local computer , i didnt add any custom header and use simple httpserver module from python .

python -m SimpleHTTPServer 12345
Serving HTTP on 0.0.0.0 port 12345 ...
192.168.9.150 - - [30/Dec/2020 10:24:14] "GET /test.csv HTTP/1.1" 200 -
192.168.9.150 - - [30/Dec/2020 10:24:25] "GET /test.csv HTTP/1.1" 200 -

still get the error.
can it be ... file encoding (CR/LF windows/unix style ? )
or the python http module is not sending correctly some expected header maybe ? 
i ll give a try with another http server. (i definitely upvote for local csv upload in order to ease the use of grafana for "one shot users that are not admin or powerusers or database gurus".

Edit : redid everything from scratch and had success , now have to guess how to decode the time from my csv , is there some method to convert to C time or something , (how d you know wich is month/day, what is the separator for hour minues etc etc ? what is the expected format ?

**Comment by marcusolsson** [comment]
I created a GitHub Gist with your CSV content which seems to work.

<img width="1563" alt="Screen Shot 2020-12-30 at 10 54 16" src="https://user-images.githubusercontent.com/8396880/103343869-5f9e8300-4a8d-11eb-9186-0eafb39a925e.png">

The plugin uses a fairly naïve approach when it comes to detecting timestamps. It basically tries to parse a [list of common formats](https://github.com/marcusolsson/grafana-csv-datasource/blob/b9980b21199f968a2da47fba62b8bed96e0da430/pkg/datasource.go#L366-L398), among which yours is present. One thing to note here is that since your data doesn't contain time zone information, it will assume UTC.

Local CSV is a heavily requested feature, and I will start working on it during this week.

**Comment by marcusolsson** [comment]
Here's a schema that seems to work for your data:

<img width="1387" alt="Screen Shot 2020-12-30 at 11 04 35" src="https://user-images.githubusercontent.com/8396880/103344410-cff9d400-4a8e-11eb-80a6-e3235091d948.png">

**Comment by ouinouin** [comment]
i ll give a try next week, I tried to do exactly that but couldnt get a graph, I ll get on it again.
the final apparoach is to be able to make grafana eating back is own CSV's :-) (this csv was exported bay the inspect menu of grafana.

**Comment by ouinouin** [comment]
![Capture d’écran du 2021-01-04 12-03-25](https://user-images.githubusercontent.com/6713759/103528856-f94aa380-4e84-11eb-9eaf-6d1bcb780856.png)
managed to graph.
this means Grafana is able to eat its own food since this CSV was created by grafana !!! (in the inspect menu you have options to export data as a CSV.
this means also with the sole installation of grafana you are able to dig inside all the PLC/industrial softwares that only knows the excel/csv export formats.
and this is to my mind very important since you can quickly export a dataset and share it to another guy with grafana without the need of linking to the database (this problematic is very common on industries , ppl in offices just need something like a viewer but do not necessary have a realtime direct access to the data produced by the process/ machines.

@marcusolsson the next big showstopper for the CSV's may be to let the user choose the date format (in order not to miss the impossible to guess automatically : month and day permutation on some locales ( MM/DD/YYYY vs DD/MM/YYYY).
do you want me to raise a special issue for this point in order to trace it better ?

**Comment by marcusolsson** [comment]
Currently, the plugin detects date format by simply attempting to parse different formats.

https://github.com/marcusolsson/grafana-csv-datasource/blob/c0461b120353106d93f588b5fbef4f58b00572e5/pkg/csv.go#L185-L229

Hopefully, most date formats should already be covered, and I'd be happy to consider adding more formats. But yes, for more obscure date formats you'd have to provide an explicit format string. I was hoping to avoid it for UX purposes, but if there's enough people asking for this, I'd be willing to add it. If this would be useful to you, please create another issue where we can discuss this further.

I'm closing this issue as it seems like you got it working in the end. Let me know if the problem reappears and I'll reopen it!
